import {
  IArticle,
  IBook,
  ICode,
  IEdit,
  IQuestion,
  ISyntax,
  ITransform,
  IUserFilled,
  IMenu,
  ITag,
  IExpand,
  IClose,
  IArrowDown,
  IArrowUp,
  ICopy,
  IRefreshRight,
  IUpdate,
  IGithub,
  IPlus,
  IHistory,
  ISend,
  ITagFilled,
  ISet,
  IExit,
  ICheckOutlined,
  IOct,
  ICloseCircle,
} from "./index";

export default {
  article: IArticle,
  book: IBook,
  code: ICode,
  edit: IEdit,
  question: IQuestion,
  syntax: ISyntax,
  transform: ITransform,
  userfilled: IUserFilled,
  menu: IMenu,
  tag: ITag,
  expand: IExpand,
  close: IClose,
  arrowdown: IArrowDown,
  arrowup: IArrowUp,
  copy: ICopy,
  refreshRight: IRefreshRight,
  update: IUpdate,
  github: IGithub,
  plus: IPlus,
  history: IHistory,
  send: ISend,
  tagFilled: ITagFilled,
  set: ISet,
  exit: IExit,
  checkOutlined: ICheckOutlined,
  IMoreOutlined: ICheckOutlined,
  IOct: IOct,
  ICloseCircle: ICloseCircle,
};
